### PR TITLE
fix #249 - fix session handler lock key prefix

### LINKED ISSUE #249: LockKey doesn't get prefixed with prefix properly + patch
The `RedisSessionHandler::$lockKey` gets prefixed with just the prefix without the colon (`$this->prefix.$lockKey`), but every other session related sessions get prefixed with `$this->prefix.':'.$sessionId`). Lock key should also have a colon after the prefix (`$this->prefix.':'.$this->lockKey`). I've generated a patch to fix this. I'd give you a PR but I'm not sure where to point the PR to. You can apply this by saving it as `diff.patch` and running: `patch -p0 < diff.patch`.

This was asked about in #181 as well. There's already a PR to master #158 but this is for 1.1.

Below is the patch:

``` patch
diff --git Session/Storage/Handler/RedisSessionHandler.php Session/Storage/Handler/RedisSessionHandler.php
index b6ad274..092ebfd 100644
--- Session/Storage/Handler/RedisSessionHandler.php
+++ Session/Storage/Handler/RedisSessionHandler.php
@@ -108,10 +108,10 @@ class RedisSessionHandler implements \SessionHandlerInterface

         $this->lockKey = $sessionId.'.lock';
         for ($i=0;$i<$attempts;$i++) {
-            $success = $this->redis->setnx($this->prefix.$this->lockKey, '1');
+            $success = $this->redis->setnx($this->getLockKey(), '1');
             if ($success) {
                 $this->locked = true;
-                $this->redis->expire($this->prefix.$this->lockKey, $this->lockMaxWait + 1);
+                $this->redis->expire($this->getLockKey(), $this->lockMaxWait + 1);
                 return true;
             }
             usleep($this->spinLockWait);
@@ -122,7 +122,7 @@ class RedisSessionHandler implements \SessionHandlerInterface

     private function unlockSession()
     {
-        $this->redis->del($this->prefix.$this->lockKey);
+        $this->redis->del($this->getLockKey());
         $this->locked = false;
     }

@@ -213,6 +213,11 @@ class RedisSessionHandler implements \SessionHandlerInterface
         return $this->prefix . ':' . $sessionId;
     }

+    public function getLockKey()
+    {
+        return $this->getRedisKey($this->lockKey);
+    }
+
     /**
      * Destructor
      */
```

### PR DESCRIPTION
**Pull request by B-Galati**

### CODE REVIEW

**Comment by Seldaek** [comment]
Looks fine to me but it's just a code cleanup, I don't see how it fixes that issue.

**Comment by B-Galati** [comment]
@Seldaek Me neither, I think I am misunderstanding something :D

I'll check it out again tomorrow. 

Thx!

File: Session/Storage/Handler/RedisSessionHandler.php [hunk 1]
```diff
@@ -194,7 +193,7 @@ protected function lockSession($sessionId)
         $attempts = (1000000 / $this->spinLockWait) * $this->lockMaxWait;
 
         $this->token = uniqid();
-        $this->lockKey = $sessionId.'.lock';
+        $this->lockKey = $this->getRedisKey($sessionId).'.lock';
```
Comment (B-Galati) [inline Session/Storage/Handler/RedisSessionHandler.php]: @Seldaek in fact this line make sure the prefix is also applied to the lock. I'll add some test.
Is there anything else?

Comment (Seldaek) [reply Session/Storage/Handler/RedisSessionHandler.php]: I see that but before getRedisKey() was applied to every usage of $this->lockKey so I don't see how it changes anything.

Comment (B-Galati) [reply Session/Storage/Handler/RedisSessionHandler.php]: Got it now! Thx!

**Comment by B-Galati** [comment]
@Seldaek @curry684 I think I don't get what the issue is or there is no issue left.

This is what I have in logs when I logged in. Does it look ok to you?

image

**Comment by B-Galati** [comment]
Here is the full log trace :

```
Feb 21 11:18:14 |INFO | REQUES Matched route "app_login". method="POST" request_uri="http://localhost:8002/login" route="app_login" route_parameters={"_controller":"App\\Controller\\SecurityController::login","_route":"app_login"}
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "SET benoitl93kq4j8a80qf22rul84orl432.lock 5c6e7ae6795bc NX PX 30001"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "GET benoitl93kq4j8a80qf22rul84orl432"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "DEL benoitl93kq4j8a80qf22rul84orl432"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "SET benoith1fb387n0ib4lkvhqfl85s3k3s.lock 5c6e7ae679b09 NX PX 30001"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "GET benoith1fb387n0ib4lkvhqfl85s3k3s"
Feb 21 11:18:14 |INFO | SECURI User has been authenticated successfully. username="benoit"
Feb 21 11:18:14 |DEBUG| SECURI Stored the security token in the session. key="_security_main"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "SETEX benoitmvbeq4p1oga4hmnd6bujmpkqos 1200 _sf2_attributes|a:2:{s:18:"_csrf/authenticate";s:43:"D5RH7v0OUUjvBbdOJGmjFa0vejTPyHLP_O88bp6Rats";s:14:"_security_main";s:845:"C:74:"Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken":757:{a:3:{i:0;N;i:1;s:4:"main";i:2;a:4:{i:0;O:41:"Symfony\Component\Security\Core\User\User":7:{s:51:"Symfony\Component\Security\Core\User\Userusername";s:6:"benoit";s:51:"Symfony\Component\Security\Core\User\Userpassword";s:6:"benoit";s:50:"Symfony\Component\Security\Core\User\Userenabled";b:1;s:60:"Symfony\Component\Security\Core\User\UseraccountNonExpired";b:1;s:64:"Symfony\Component\Security\Core\User\UsercredentialsNonExpired";b:1;s:59:"Symfony\Component\Security\Core\User\UseraccountNonLocked";b:1;s:48:"Symfony\Component\Security\Core\User\Userroles";a:1:{i:0;s:9:"ROLE_USER";}}i:1;b:1;i:2;a:1:{i:0;O:41:"Symfony\Component\Security\Core\Role\Role":1:{s:47:"Symfony\Component\Security\Core\Role\Rolerole";s:9:"ROLE_USER";}}i:3;a:0:{}}}}";}_sf2_meta|a:3:{s:1:"u";i:1550744294;s:1:"c";i:1550744294;s:1:"l";s:1:"0";}"
Feb 21 11:18:14 |INFO | REQUES Matched route "default". method="GET" request_uri="http://localhost:8002/" route="default" route_parameters={"_controller":"App\\Controller\\DefaultController::index","_route":"default"}
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "SET benoitmvbeq4p1oga4hmnd6bujmpkqos.lock 5c6e7ae688f36 NX PX 30001"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "GET benoitmvbeq4p1oga4hmnd6bujmpkqos"
Feb 21 11:18:14 |DEBUG| SECURI Read existing security token from the session. key="_security_main" token_class="Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"
Feb 21 11:18:14 |DEBUG| SECURI User was reloaded from a user provider. provider="Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider" username="benoit"
Feb 21 11:18:14 |DEBUG| SECURI Stored the security token in the session. key="_security_main"
Feb 21 11:18:14 |DEBUG| SNC_RE Executing command "EXPIRE benoitmvbeq4p1oga4hmnd6bujmpkqos 1200"
```

**Comment by B-Galati** [comment]
@curry684 @Seldaek Double check this morning. Everything looks good to me before this PR and after this PR.
Maybe I am missing something.

**Comment by curry684** [comment]
The issue is 3 years old, and @Seldaek already rebuilt the session handler for 3. I think it was sort of fixed 'along the way' and is only an issue in 2.x, which makes it doubtful if we want to bother fixing it.

**Comment by B-Galati** [comment]
So let's merge this one for the little clean-up and say it is fixed? Is it ok for you @curry684?

**Comment by curry684** [comment]
^^ 👍   😄
