### PR TITLE
fix #498 - Add read_timeout connection option to phpredis

### LINKED ISSUE #498: Option read_write_timeout is not working with phpredis
When using phpredis and read_write_timeout option is set, the options is not passed to redis connect method.

### PR DESCRIPTION
**Pull request by B-Galati**
fix #498

### CODE REVIEW

**Comment by B-Galati** [comment]
@agus-k Could you let me know if it's ok for you please?

**Comment by agus-k** [comment]
I'm getting [RedisException]:Redis server went away on the setOption line for some reason. I'm using phpredis v3.1.6. What version are you using?

**Comment by B-Galati** [comment]
Same version. Do you have the same behavior with `bin/console -vn redis:flushall`

**Comment by agus-k** [comment]
`bin/console -vn redis:flushall` looks OK on my end.

**Comment by B-Galati** [comment]
@agus-k So when does this error occured in your workflow? Any stack trace?

File: Factory/PhpredisClientFactoryTest.php [hunk 1]
```diff
@@ -45,13 +45,15 @@ public function testCreateFullConfig()
...
                 'serialization' => 'php',
+                'read_write_timeout' => 4,
             ),
             'alias_test'
         );
 
         $this->assertInstanceOf('\Snc\RedisBundle\Client\Phpredis\Client', $client);
         $this->assertSame('toto', $client->getOption(\Redis::OPT_PREFIX));
         $this->assertSame(1, $client->getOption(\Redis::OPT_SERIALIZER));
+        $this->assertSame(4., $client->getOption(\Redis::OPT_READ_TIMEOUT));
```
Comment (OskarStark) [inline Factory/PhpredisClientFactoryTest.php]: Why the dot after 4?

Comment (B-Galati) [reply Factory/PhpredisClientFactoryTest.php]: To say it's a float and not an int. Without the dot, the test failed because it returns a float.
This option is a float in the doc of phpredis.

**Comment by agus-k** [comment]
> @agus-k So when does this error occured in your workflow? Any stack trace?

My bad, it was my mistake in a hurry. I double checked after pulling your commit. It works on my end. I'll close my PR. Thank you for the fix.

**Comment by B-Galati** [comment]
@agus-k Nice, thanks for letting us know!
